import src.sqliteObjects as sqliteObjects
import pandas as pd

# Creating/Opening the database file.
bwcDB = sqliteObjects.SQLiteDB('database/bwcDB.db')

interactions = bwcDB.createTable('interactions', { # SETTING UP TABLES IN THE DB
    "index" : "INTEGER UNIQUE",
    "completed" : "TEXT DEFAULT 'NO'",
    "tri_interaction_key": "INTEGER PRIMARY KEY",
    "tri_incident_number": "TEXT DEFAULT NULL",
    "tri_interaction_number": "TEXT DEFAULT NULL",
    "mos_command_description": "TEXT DEFAULT NULL",
    "mos_rank_code": "TEXT DEFAULT NULL",
    "mos_full_name": "TEXT DEFAULT NULL",
    "mos_tax_number": "TEXT DEFAULT NULL",
    "occurrence_date": "TEXT DEFAULT NULL",
    "occurrence_time": "TEXT DEFAULT NULL",
    "create_timestamp": "TEXT DEFAULT NULL",
    "report_timestamp": "TEXT DEFAULT NULL",
    "effective_timestamp": "TEXT DEFAULT NULL",
    "tri_level": "TEXT DEFAULT NULL",
    "tri_voided_flag": "TEXT DEFAULT NULL",
    "endorsement_timestamp": "TEXT DEFAULT NULL",
    "encounter_type_description": "TEXT DEFAULT NULL",
    "person_type_code": "TEXT DEFAULT NULL",
    "mos_command_code": "TEXT DEFAULT NULL",
    "boro": "TEXT DEFAULT NULL",
    "mos_tri_role_description": "TEXT DEFAULT NULL",
    "injury_sustained_flag": "TEXT DEFAULT NULL",
    "bwc_video_flag": "TEXT DEFAULT NULL",
    "bwc_viewed_flag": "TEXT DEFAULT NULL",
    "mos_on_duty_flag": "TEXT DEFAULT NULL",
    "mos_in_uniform_flag": "TEXT DEFAULT NULL",
    "mos_worn_camera_flag": "TEXT DEFAULT NULL",
    "weapon_used_code": "TEXT DEFAULT NULL",
    "action_prohibited_by_pg_221_01_flag": "TEXT DEFAULT NULL",
    "alleged_suspected_excessive_force_flag": "TEXT DEFAULT NULL",
    "fam_none_flag": "TEXT DEFAULT NULL",
    "fam_hand_strike_flag": "TEXT DEFAULT NULL",
    "fam_object_strike_flag": "TEXT DEFAULT NULL",
    "fam_foot_strike_flag": "TEXT DEFAULT NULL",
    "fam_menacing_brandishing_weapon_flag": "TEXT DEFAULT NULL",
    "fam_object_thrown_flag": "TEXT DEFAULT NULL",
    "fam_wrestling_grappling_flag": "TEXT DEFAULT NULL",
    "fam_assault_with_knife_sharp_object_flag": "TEXT DEFAULT NULL",
    "fam_discharged_firearm_at_officer_flag": "TEXT DEFAULT NULL",
    "fam_pushing_shoving_flag": "TEXT DEFAULT NULL",
    "fam_mos_self_inflicted_flag": "TEXT DEFAULT NULL",
    "fam_mos_injured_attempting_to_apprehend_control_subject_flag": "TEXT DEFAULT NULL",
    "fam_bitten_flag": "TEXT DEFAULT NULL",
    "fam_physical_harrassment_flag": "TEXT DEFAULT NULL",
    "fam_active_resistance_flag": "TEXT DEFAULT NULL",
    "fam_intentionally_spitting_bleeding_flag": "TEXT DEFAULT NULL",
    "i_fam_other_flag": "TEXT DEFAULT NULL",
    "i_fam_other_description": "TEXT DEFAULT NULL",
    "i_ism_injury_sustained_by_mos_none_flag": "TEXT DEFAULT NULL",
    "i_ism_minor_swelling_flag": "TEXT DEFAULT NULL",
    "i_ism_contusions_flag": "TEXT DEFAULT NULL",
    "i_ism_significant_contusions_flag": "TEXT DEFAULT NULL",
    "i_ism_complaint_of_substantial_pain_flag": "TEXT DEFAULT NULL",
    "i_ism_lacerations_requiring_sutures_flag": "TEXT DEFAULT NULL",
    "i_ism_broken_fractured_bones_flag": "TEXT DEFAULT NULL",
    "i_ism_gunshot_wound_flag": "TEXT DEFAULT NULL",
    "i_ism_heart_attack_stroke_aneurysm_flag": "TEXT DEFAULT NULL",
    "i_ism_killed_flag": "TEXT DEFAULT NULL",
    "i_ism_burn_flag": "TEXT DEFAULT NULL",
    "i_ism_canine_bite_flag": "TEXT DEFAULT NULL",
    "i_ism_possible_internal_injury_flag": "TEXT DEFAULT NULL",
    "i_ism_loss_of_body_part_flag": "TEXT DEFAULT NULL",
    "i_ism_sprain_strain_flag": "TEXT DEFAULT NULL",
    "i_ism_loss_of_tooth_teeth_flag": "TEXT DEFAULT NULL",
    "i_ism_unconscousness_flag": "TEXT DEFAULT NULL",
    "i_ism_abrasions_lacerations_flag": "TEXT DEFAULT NULL",
    "i_ism_other_condition_injury_flag": "TEXT DEFAULT NULL",
    "i_ism_other_condition_injury_description": "TEXT DEFAULT NULL",
    "rmf_not_applicable_flag": "TEXT DEFAULT NULL",
    "rmf_defense_of_self_flag": "TEXT DEFAULT NULL",
    "rmf_defense_of_other_mos_flag": "TEXT DEFAULT NULL",
    "rmf_defense_of_member_of_public_flag": "TEXT DEFAULT NULL",
    "rmf_stop_self_inflicted_harm_flag": "TEXT DEFAULT NULL",
    "rmf_fleeing_suspect_flag": "TEXT DEFAULT NULL",
    "rmf_overcome_resistance_or_aggresion_flag": "TEXT DEFAULT NULL",
    "rmf_subject_armed_with_weapon_flag": "TEXT DEFAULT NULL",
    "rmf_unintentional_flag": "TEXT DEFAULT NULL",
    "fmt_no_force_used": "TEXT DEFAULT NULL",
    "fmt_conducted_electrical_weapon_drive_stun_flag": "TEXT DEFAULT NULL",
    "fmt_conducted_electrical_weapon_probes_flag": "TEXT DEFAULT NULL",
    "fmt_hand_strike_flag": "TEXT DEFAULT NULL",
    "fmt_foot_strike_flag": "TEXT DEFAULT NULL",
    "fmt_forcible_take_down": "TEXT DEFAULT NULL",
    "fmt_oc_spray_flag": "TEXT DEFAULT NULL",
    "fmt_restraining_mesh_blanket_flag": "TEXT DEFAULT NULL",
    "fmt_impact_weapon_flag": "TEXT DEFAULT NULL",
    "fmt_police_canine_bite_flag": "TEXT DEFAULT NULL",
    "fmt_discharged_firearm_flag": "TEXT DEFAULT NULL",
    "fmt_intentionally_struck_subject_with_vehicle_flag": "TEXT DEFAULT NULL",
    "fmt_wrestling_grappling_flag": "TEXT DEFAULT NULL",
    "fmt_other_force_flag": "TEXT DEFAULT NULL",
    "fmt_other_force_desc": "TEXT DEFAULT NULL",
    "person_type_code": "TEXT DEFAULT NULL",
    "role_description": "TEXT DEFAULT NULL",
    "person_full_name": "TEXT DEFAULT NULL",
    "subject_injured_flag": "TEXT DEFAULT NULL",
    "subject_resisted_flag": "TEXT DEFAULT NULL",
    "subject_used_force_flag": "TEXT DEFAULT NULL",
    "medical_attention_needed": "TEXT DEFAULT NULL",
    "ems_treated_description": "TEXT DEFAULT NULL",
    "summons_issued_flag": "TEXT DEFAULT NULL",
    "arrest_made_flag": "TEXT DEFAULT NULL",
    "arrest_number": "TEXT DEFAULT NULL",
    "top_charge": "TEXT DEFAULT NULL",
    "i_csi_no_injury_flag": "TEXT DEFAULT NULL",
    "i_csi_broken_fractured_bones_flag": "TEXT DEFAULT NULL",
    "i_csi_complaint_of_substential_pain_flag": "TEXT DEFAULT NULL",
    "i_csi_gunshot_wound_flag": "TEXT DEFAULT NULL",
    "i_csi_heart_attack_stroke_aneurysm_flag": "TEXT DEFAULT NULL",
    "i_csi_lacerations_requiring_stitches_staples_flag": "TEXT DEFAULT NULL",
    "i_csi_loss_of_tooth_teeth_flag": "TEXT DEFAULT NULL",
    "i_csi_minor_contusions_flag": "TEXT DEFAULT NULL",
    "i_csi_minor_lacerations_abrasion_flag": "TEXT DEFAULT NULL",
    "i_csi_minor_swelling_flag": "TEXT DEFAULT NULL",
    "i_csi_subject_civilian_bystander_died_flag": "TEXT DEFAULT NULL",
    "i_csi_subject_civilian_bystander_likely_to_die_flag": "TEXT DEFAULT NULL",
    "i_csi_unconsciousness_flag": "TEXT DEFAULT NULL",
    "i_csi_unknown_flag": "TEXT DEFAULT NULL",
    "i_csi_other_condition_requiring_hospital_admission_flag": "TEXT DEFAULT NULL",
    "i_csi_other_condition_description": "TEXT DEFAULT NULL",
    "ism_yes_flag": "TEXT DEFAULT NULL",
    "db_category": "TEXT DEFAULT NULL"
})

interactionsMASTER = bwcDB.createTable('interactionsMASTER', {
    "index" : "INTEGER UNIQUE",
    "completed" : "TEXT DEFAULT 'NO'",
    "tri_interaction_key": "INTEGER PRIMARY KEY",
    "tri_incident_number": "TEXT DEFAULT NULL",
    "tri_interaction_number": "TEXT DEFAULT NULL",
    "mos_command_description": "TEXT DEFAULT NULL",
    "mos_rank_code": "TEXT DEFAULT NULL",
    "mos_full_name": "TEXT DEFAULT NULL",
    "mos_tax_number": "TEXT DEFAULT NULL",
    "occurrence_date": "TEXT DEFAULT NULL",
    "occurrence_time": "TEXT DEFAULT NULL",
    "create_timestamp": "TEXT DEFAULT NULL",
    "report_timestamp": "TEXT DEFAULT NULL",
    "effective_timestamp": "TEXT DEFAULT NULL",
    "tri_level": "TEXT DEFAULT NULL",
    "tri_voided_flag": "TEXT DEFAULT NULL",
    "endorsement_timestamp": "TEXT DEFAULT NULL",
    "encounter_type_description": "TEXT DEFAULT NULL",
    "person_type_code": "TEXT DEFAULT NULL",
    "mos_command_code": "TEXT DEFAULT NULL",
    "boro": "TEXT DEFAULT NULL",
    "mos_tri_role_description": "TEXT DEFAULT NULL",
    "injury_sustained_flag": "TEXT DEFAULT NULL",
    "bwc_video_flag": "TEXT DEFAULT NULL",
    "bwc_viewed_flag": "TEXT DEFAULT NULL",
    "mos_on_duty_flag": "TEXT DEFAULT NULL",
    "mos_in_uniform_flag": "TEXT DEFAULT NULL",
    "mos_worn_camera_flag": "TEXT DEFAULT NULL",
    "weapon_used_code": "TEXT DEFAULT NULL",
    "action_prohibited_by_pg_221_01_flag": "TEXT DEFAULT NULL",
    "alleged_suspected_excessive_force_flag": "TEXT DEFAULT NULL",
    "fam_none_flag": "TEXT DEFAULT NULL",
    "fam_hand_strike_flag": "TEXT DEFAULT NULL",
    "fam_object_strike_flag": "TEXT DEFAULT NULL",
    "fam_foot_strike_flag": "TEXT DEFAULT NULL",
    "fam_menacing_brandishing_weapon_flag": "TEXT DEFAULT NULL",
    "fam_object_thrown_flag": "TEXT DEFAULT NULL",
    "fam_wrestling_grappling_flag": "TEXT DEFAULT NULL",
    "fam_assault_with_knife_sharp_object_flag": "TEXT DEFAULT NULL",
    "fam_discharged_firearm_at_officer_flag": "TEXT DEFAULT NULL",
    "fam_pushing_shoving_flag": "TEXT DEFAULT NULL",
    "fam_mos_self_inflicted_flag": "TEXT DEFAULT NULL",
    "fam_mos_injured_attempting_to_apprehend_control_subject_flag": "TEXT DEFAULT NULL",
    "fam_bitten_flag": "TEXT DEFAULT NULL",
    "fam_physical_harrassment_flag": "TEXT DEFAULT NULL",
    "fam_active_resistance_flag": "TEXT DEFAULT NULL",
    "fam_intentionally_spitting_bleeding_flag": "TEXT DEFAULT NULL",
    "i_fam_other_flag": "TEXT DEFAULT NULL",
    "i_fam_other_description": "TEXT DEFAULT NULL",
    "i_ism_injury_sustained_by_mos_none_flag": "TEXT DEFAULT NULL",
    "i_ism_minor_swelling_flag": "TEXT DEFAULT NULL",
    "i_ism_contusions_flag": "TEXT DEFAULT NULL",
    "i_ism_significant_contusions_flag": "TEXT DEFAULT NULL",
    "i_ism_complaint_of_substantial_pain_flag": "TEXT DEFAULT NULL",
    "i_ism_lacerations_requiring_sutures_flag": "TEXT DEFAULT NULL",
    "i_ism_broken_fractured_bones_flag": "TEXT DEFAULT NULL",
    "i_ism_gunshot_wound_flag": "TEXT DEFAULT NULL",
    "i_ism_heart_attack_stroke_aneurysm_flag": "TEXT DEFAULT NULL",
    "i_ism_killed_flag": "TEXT DEFAULT NULL",
    "i_ism_burn_flag": "TEXT DEFAULT NULL",
    "i_ism_canine_bite_flag": "TEXT DEFAULT NULL",
    "i_ism_possible_internal_injury_flag": "TEXT DEFAULT NULL",
    "i_ism_loss_of_body_part_flag": "TEXT DEFAULT NULL",
    "i_ism_sprain_strain_flag": "TEXT DEFAULT NULL",
    "i_ism_loss_of_tooth_teeth_flag": "TEXT DEFAULT NULL",
    "i_ism_unconscousness_flag": "TEXT DEFAULT NULL",
    "i_ism_abrasions_lacerations_flag": "TEXT DEFAULT NULL",
    "i_ism_other_condition_injury_flag": "TEXT DEFAULT NULL",
    "i_ism_other_condition_injury_description": "TEXT DEFAULT NULL",
    "rmf_not_applicable_flag": "TEXT DEFAULT NULL",
    "rmf_defense_of_self_flag": "TEXT DEFAULT NULL",
    "rmf_defense_of_other_mos_flag": "TEXT DEFAULT NULL",
    "rmf_defense_of_member_of_public_flag": "TEXT DEFAULT NULL",
    "rmf_stop_self_inflicted_harm_flag": "TEXT DEFAULT NULL",
    "rmf_fleeing_suspect_flag": "TEXT DEFAULT NULL",
    "rmf_overcome_resistance_or_aggresion_flag": "TEXT DEFAULT NULL",
    "rmf_subject_armed_with_weapon_flag": "TEXT DEFAULT NULL",
    "rmf_unintentional_flag": "TEXT DEFAULT NULL",
    "fmt_no_force_used": "TEXT DEFAULT NULL",
    "fmt_conducted_electrical_weapon_drive_stun_flag": "TEXT DEFAULT NULL",
    "fmt_conducted_electrical_weapon_probes_flag": "TEXT DEFAULT NULL",
    "fmt_hand_strike_flag": "TEXT DEFAULT NULL",
    "fmt_foot_strike_flag": "TEXT DEFAULT NULL",
    "fmt_forcible_take_down": "TEXT DEFAULT NULL",
    "fmt_oc_spray_flag": "TEXT DEFAULT NULL",
    "fmt_restraining_mesh_blanket_flag": "TEXT DEFAULT NULL",
    "fmt_impact_weapon_flag": "TEXT DEFAULT NULL",
    "fmt_police_canine_bite_flag": "TEXT DEFAULT NULL",
    "fmt_discharged_firearm_flag": "TEXT DEFAULT NULL",
    "fmt_intentionally_struck_subject_with_vehicle_flag": "TEXT DEFAULT NULL",
    "fmt_wrestling_grappling_flag": "TEXT DEFAULT NULL",
    "fmt_other_force_flag": "TEXT DEFAULT NULL",
    "fmt_other_force_desc": "TEXT DEFAULT NULL",
    "person_type_code": "TEXT DEFAULT NULL",
    "role_description": "TEXT DEFAULT NULL",
    "person_full_name": "TEXT DEFAULT NULL",
    "subject_injured_flag": "TEXT DEFAULT NULL",
    "subject_resisted_flag": "TEXT DEFAULT NULL",
    "subject_used_force_flag": "TEXT DEFAULT NULL",
    "medical_attention_needed": "TEXT DEFAULT NULL",
    "ems_treated_description": "TEXT DEFAULT NULL",
    "summons_issued_flag": "TEXT DEFAULT NULL",
    "arrest_made_flag": "TEXT DEFAULT NULL",
    "arrest_number": "TEXT DEFAULT NULL",
    "top_charge": "TEXT DEFAULT NULL",
    "i_csi_no_injury_flag": "TEXT DEFAULT NULL",
    "i_csi_broken_fractured_bones_flag": "TEXT DEFAULT NULL",
    "i_csi_complaint_of_substential_pain_flag": "TEXT DEFAULT NULL",
    "i_csi_gunshot_wound_flag": "TEXT DEFAULT NULL",
    "i_csi_heart_attack_stroke_aneurysm_flag": "TEXT DEFAULT NULL",
    "i_csi_lacerations_requiring_stitches_staples_flag": "TEXT DEFAULT NULL",
    "i_csi_loss_of_tooth_teeth_flag": "TEXT DEFAULT NULL",
    "i_csi_minor_contusions_flag": "TEXT DEFAULT NULL",
    "i_csi_minor_lacerations_abrasion_flag": "TEXT DEFAULT NULL",
    "i_csi_minor_swelling_flag": "TEXT DEFAULT NULL",
    "i_csi_subject_civilian_bystander_died_flag": "TEXT DEFAULT NULL",
    "i_csi_subject_civilian_bystander_likely_to_die_flag": "TEXT DEFAULT NULL",
    "i_csi_unconsciousness_flag": "TEXT DEFAULT NULL",
    "i_csi_unknown_flag": "TEXT DEFAULT NULL",
    "i_csi_other_condition_requiring_hospital_admission_flag": "TEXT DEFAULT NULL",
    "i_csi_other_condition_description": "TEXT DEFAULT NULL",
    "ism_yes_flag": "TEXT DEFAULT NULL",
    "db_category": "TEXT DEFAULT NULL"
})

entries = bwcDB.createTable('entries', {
    "entry_key": "INTEGER PRIMARY KEY AUTOINCREMENT",
    "tri_index" : "INTEGER UNIQUE",
    "tri_interaction_key": "INTEGER UNIQUE",
    "tri_incident_number": "TEXT DEFAULT NULL",
    "tri_interaction_number": "TEXT DEFAULT NULL",
    "user" : "TEXT DEFAULT NULL",
    "reviewed" : "TEXT DEFAULT NULL",
    "video_of_force_incident": "TEXT DEFAULT NULL",
    "good" : "TEXT DEFAULT NULL",
    "bwc_command": "TEXT DEFAULT NULL",
    "bwc_user_at_time_of_incident": "TEXT DEFAULT NULL",
    "force_incident_serial_number": "TEXT DEFAULT NULL",
    "force_incident_link" : "TEXT DEFAULT NULL",
    "late_activation": "TEXT DEFAULT NULL",
    "early_deactivation": "TEXT DEFAULT NULL",
    "shared_with_ada": "TEXT DEFAULT NULL",
    "video_categorized_as_force_incident": "TEXT DEFAULT NULL",
    "tri_number_entered_in_metadata": "TEXT DEFAULT NULL",
    "multiple_videos_incident_by_user": "TEXT DEFAULT NULL",
    "all_evidence_serial_numbers": "TEXT DEFAULT NULL",
    "all_evidence_links" : "TEXT DEFAULT NULL",
    "dt_created" : "TEXT DEFAULT NULL",
    "dt_committed" : "TEXT DEFAULT NULL"
}, extras=['FOREIGN KEY(tri_interaction_key) REFERENCES interactions(tri_interaction_key)'])

entriesMASTER = bwcDB.createTable('entriesMASTER', {
    "entry_key": "INTEGER PRIMARY KEY AUTOINCREMENT",
    "tri_index" : "INTEGER UNIQUE",
    "tri_interaction_key": "INTEGER UNIQUE",
    "tri_incident_number": "TEXT DEFAULT NULL",
    "tri_interaction_number": "TEXT DEFAULT NULL",
    "user" : "TEXT DEFAULT NULL",
    "reviewed" : "TEXT DEFAULT NULL",
    "video_of_force_incident": "TEXT DEFAULT NULL",
    "good" : "TEXT DEFAULT NULL",
    "bwc_command": "TEXT DEFAULT NULL",
    "bwc_user_at_time_of_incident": "TEXT DEFAULT NULL",
    "force_incident_serial_number": "TEXT DEFAULT NULL",
    "force_incident_link" : "TEXT DEFAULT NULL",
    "late_activation": "TEXT DEFAULT NULL",
    "early_deactivation": "TEXT DEFAULT NULL",
    "shared_with_ada": "TEXT DEFAULT NULL",
    "video_categorized_as_force_incident": "TEXT DEFAULT NULL",
    "tri_number_entered_in_metadata": "TEXT DEFAULT NULL",
    "multiple_videos_incident_by_user": "TEXT DEFAULT NULL",
    "all_evidence_serial_numbers": "TEXT DEFAULT NULL",
    "all_evidence_links" : "TEXT DEFAULT NULL",
    "dt_created" : "TEXT DEFAULT NULL",
    "dt_committed" : "TEXT DEFAULT NULL"
}, extras=['FOREIGN KEY(tri_interaction_key) REFERENCES interactions(tri_interaction_key)'])
